api = "0.2"

[buildpack]
id = "paketo-buildpacks/dotnet-core-execute"
name = "Paketo .NET Core Execute Buildpack"
version = "{{ .Version }}"
homepage = "https://github.com/paketo-buildpacks/dotnet-core-execute"

[metadata]
include_files = ["bin/build","bin/detect","bin/run", "buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
