api = "0.2"

[buildpack]
id = "paketo-buildpacks/dotnet-execute"
name = "Paketo .NET Execute Buildpack"
version = "{{ .Version }}"
homepage = "https://github.com/paketo-buildpacks/dotnet-execute"

[metadata]
include-files = ["bin/build","bin/detect","bin/run", "buildpack.toml"]
pre-package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
